<?php include 'pdf-completo/header-footer.php'; ?>	
	<?php if($cliente['sexo'] == 'Hombre'){ ?>
	<h1 class="tc_azul">BIENVENIDO</h1>
	<p><strong>Estimado <?php echo $cliente['nombre']; ?> </strong></p>
	<?php }else{ ?>
		<h1 class="tc_azul">BIENVENIDA</h1>
		<p><strong>Estimada <?php echo $cliente['nombre']; ?> </strong></p>
	<?php }  ?>	
		<div class="contenido_texto">
		<p>Usted acude a nosotros porque ha considerado que debe realizar un control sobre su alimentación,aprovechamos para darle la bienvenida y animarle a aprovechar esta oportunidad para mejorar de manera notoria su calidad de vida. No debe tener ninguna duda de que puede mejorar, tan solo necesita un poco de constancia y descubrirá un progreso importante en poco tiempo.</p>
		<p>Tanto los procedimientos para realizar los estudios antropomórficos como su resultado final, la dieta a realizar, siguen los parámetros marcados por las más importantes instituciones y entidades que trabajan en el campo de la nutrición tanto a nivel nacional como internacional. La Dieta proporcionada nada tiene que ver con las famosas ?dietas milagro? con aparentes beneficios a corto plazo en términos de pérdidas de peso, pero que tienen efectos secundarios claramente nocivos para la salud y un conocido efecto rebote que hace que termine con más kilos de los que tenía antes de comenzar la dieta.</p>
		<p>Con nuestro asesoramiento tiene la oportunidad de cambiar sus hábitos alimenticios, mejorar su ingesta, incluso si lo desea descubrir nuevos platos que le pueden proporcionar una gran satisfacción personal, no debe pues ver la dieta como un proceso penoso y que le va a producir ansiedad, y que, incluso, va a hacer pasar hambre, la realidad es que es probable que coma más veces al día, con una alimentación más variada y más equilibrada. </p>
		<p>El estudio que le entregamos le proporciona información sobre sus necesidades en proteínas, grasas, vitaminas, minerales y el resto de componentes que necesita para una correcta alimentación.</p>
		<p>Está dieta está realizada exclusivamente para usted, se corresponde con las necesidades detectadas a partir del estudio resultado de la antropometría que ha realizado en nuestra clínica, así como de sus gustos gastronómicos, no debe utilizar está información para terceras personas porque pueden tener necesidades completamente diferenciadas y por consiguiente ocasionar un perjuicio no deseable.</p>
		<p>Realizar deporte, con moderación, contribuye a obtener resultados en un menor tiempo, para ello no necesita ser un gran deportista, siempre que ninguna lesión o enfermedad le perjudique, caminar todos los días, entre 45 y 60 minutos a una velocidad media-alta contribuirá a mejorar su calidad de vida de una manera notoria.</p>
		<p>Le comentamos brevemente algunos puntos extractados del libro del Doctor Ramón de Cangas titulado "111 Mitos y leyendas Alimentarias" publicada por Ediciones Parnaso que le pueden ser de utilidad para seguir la dieta:</p>
		<p class="tc_azul"><strong>A) Muchos creen: " Si quito la miga al pan, engorda menos"</strong></p>
		<p>¿Quién no ha quitado alguna vez la miga al pan? Como vemos que la miga es pastosa, "harinosa" etc., creemos que quitándola ahuyentamos gran parte de los males del pan. En realidad ya hemos visto que el pan no aporta tantas Kilocalorías como pensábamos. Es la corteza - todo lo contrario a lo que la gente cree y no la miga, la que aporta más Kilocalorías.</p>
		<p>¿Cómo es posible esto? Pues simplemente ocurre que la miga tiene más agua y aire que la corteza, y por eso (entre otras cosas) es más blanda y esponjosa. La corteza es más concentrada y a igualdad de peso aporta más calorías que la miga. </p>
		<p>En definitiva: no quitemos la miga al pan. No son muchas las Kilocalorías que ahorro y me estoy privando de un placer. Tampoco quitemos la corteza porque el problema no es el pan, sino las salsas que mojo o lo que el pan lleva dentro.</p>
		<p class="tc_azul"><strong>B) Dicen: " El aceite de oliva no engorda si es crudo" </strong></p>
		<p>El aceite de oliva virgen extra es una buena fuente de Vitamina E y ciertas sustancias antioxidantes, es rico en grasas monoinsaturadas que son buenas para la salud, pero lo cierto es que un gramo de aceite de oliva, o de cualquier otro tipo de aceite, aporta unas 9 kilocalorías, sea crudo o tras someterlo a una fritura. La única diferencia es que en el proceso de las frituras se generan, entre otras cosas, los llamados compuestos polares que no son saludables y que hacen que después de usarlo varias veces el aceite se deba desechar, pero eso no tiene nada que ver con que sea preferible el crudo porque aporte menos</p>
		<p>calorías. Además en el proceso de fritura se perderán sus antioxidantes etc. Pero crudo o cocinado un gramo de aceite aporta unas 9 kilocalorías, con lo que a poco que seamos generosos con su uso disparamos las Kilocalorías del plato. </p>
		<p>1 gramo de aceite aporta 9 Kilocalorías. Se recomienda tomar entre 3?5 raciones de grasas al día. Un exceso de aceite, sea como sea, disparará la energía que ingerimos.</p>
		<p class="tc_azul"><strong>C) Muchas veces hemos oído decir a alguien: " Me han dicho que tomar fruta antes de las comidas me hará adelgazar, pero que si la tomo después de la comida me engorda" </strong></p>
		<p>Es un mito muy extendido, pero la realidad es que la fruta se caracteriza por su alto contenido en agua. Debido a ello (unido a que apenas tiene grasa salvo el coco o el aguacate) su densidad energética no es demasiado alta. La fruta tiene las calorías que tiene sea tomada antes de comer, después de comer, o durante la comida. No hay ninguna razón que explique que la fruta engorde al tomarla después de comer. Se dice que tomada después de comer puede fermentar en el estómago, ¿fermentar?, fermenta la leche gracias a las bacterias lácticas, o la cerveza en el proceso llevado a cabo por levaduras, pero hablar de una fermentación de la fruta en el estómago es una idea absurda.</p>
		<p>Ingerir la fruta antes de comer el resto de alimentos no adelgaza. Únicamente puede existir una razón por la que se explique que hacer esto puede ayudar a algunas personas a controlar el peso y es el hecho de que si una persona se come la manzana antes de comer, sentirá plenitud y probablemente ingiera después menos cantidad del resto de los platos. Imaginemos que me voy a tomar una fabada asturiana de primero, un cordero asado con patatas fritas de segundo y una buena porción de tarta de queso con sirope de cacao de postre. Si yo me como dos manzanas y bebo un litro de agua un rato antes de la comida, está claro que después podré probablemente consumir la fabada, pero es muy probable que no pueda acabar el segundo plato (el cordero), o al menos con su guarnición (las patatas fritas) y me costará mucho poder consumir el postre, con lo que me ahorraré ingerir un buen puñado de Kilocalorías.</p>
		<p>Una pieza de fruta aporta exactamente las mismas Kilocalorías si la ingiero antes de comer, durante la comida, o después de la comida.</p>
		<p class="tc_azul"><strong>D) Muchas personas dicen: "El plátano engorda más que la mayoría de las frutas, por eso en muchas dietas te dan una manzana de postre y no un plátano". </strong></p>
		<p>Esta afirmación está muy extendida, incluso entre profesionales relacionados con el mundo sanitario. De hecho, en muchas dietas no se ofrecen plátanos ni uvas de postre. En verdad, retirar el plátano de las dietas hipocalóricas es absurdo y carente de toda lógica, y hacerlo significa no profundizar en la dietética lo suficiente, quedándose en una simple lectura superficial de las tablas de composición de alimentos. Y es que 100 gramos de plátano aportan más calorías que 100 gramos de manzana, sin embargo un plátano suele pesar unos 120 gramos (uno normal) y una manzana puede pesar fácilmente 230 gramos. 100 gramos de plátano son unas 90 Kilocalorías, mientras que 100 gramos de manzana aportan unas 52 kilocalorías.</p>
		<p>Si yo me tomo una manzana de un tamaño habitual que puede venir a pesar unos 230 gramos, estoy ingiriendo unas 119,6 Kilocalorías, mientras que un plátano de tamaño habitual (unos 130 gramos) me aporta unas 117 Kilocalorías. Vemos con ello que una pieza de plátano equivale a una pieza de manzana, por lo que es absurdo y carente de toda lógica retirar el plátano y las uvas (un racimo pequeño equivale también a una manzana) en una dieta, o de nuestra alimentación habitual. </p>
		<p>1 plátano equivale a 1 pieza de manzana. Podemos ver, por tanto, que es un error comparar los alimentos simplemente por su valor calórico por 100 gramos en las tablas de composición de alimentos. ¡ Debemos acostumbrarnos a comparar, entre las raciones habituales!.</p>
		</div>	